plugins {
    id "java"
    id "org.springframework.boot" version "3.4.2"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"

java {
    sourceCompatibility = "21"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.springframework.boot:spring-boot-dependencies:3.4.2")
    implementation platform('com.google.cloud:spring-cloud-gcp-dependencies:6.2.0')

    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-thymeleaf"
    implementation "com.google.cloud:spring-cloud-gcp-starter-data-datastore"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}

test {
    useJUnitPlatform()
}
